server:
  port: 8081
zuul:
  sensitive-headers: Cookie,Set-Cookie
  routes:
    client:
      path: /client/**
      serviceId: CLIENT

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
    healthcheck:
      enabled: true
spring:
  application:
    name: zuul