spring:
  application:
    name: client

server:
  port: 8087


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka
    healthcheck:
      enabled: true